### ISSUE TITLE
Iext search not working with CouchDB 3.3.2

### ISSUE THREAD

**Issue by lmorandini** [apache/couchdb-helm#134]
Since the text search does not work on the `4.4.5` version of the Helm Chart, I have forked the [clouseau-docker](https://github.com/kocolosk/clouseau-docker) repository and applied the [changes suggested here](https://github.com/apache/couchdb/issues/4369) (see the fork at [update-clouseau-2.21.6 branch](https://github.com/lmorandini/clouseau-docker/tree/update-clouseau-2.21.6)).

I then built a Docker image from it and pushed it to Docker Hub, hence a simple change to the `values.yaml` should make the text search work with CouchDB 3.3.2 using this Helm chart.

The stanza to change in the `values.yaml` is:
```
searchImage:
  repository: docker.io/lmorandini/couchdb-search
  tag: 0.2.1
  pullPolicy: IfNotPresent
```
