### ISSUE TITLE
Warning during install: Skipped value for affinity: Not a table

### ISSUE THREAD

**Issue by borigas** [apache/couchdb-helm#32]
**Describe the bug**
I get a warning `coalesce.go:160: warning: skipped value for affinity: Not a table.` when trying to install with affinity set in my values file

**Version of Helm and Kubernetes**:
Helm: 3.2.1
Kubernetes: 1.17.5

**What happened**:
When installing, I get a warning: `coalesce.go:160: warning: skipped value for affinity: Not a table.` Warnings cause my deployment pipeline to abort, so I need to get this fixed

**What you expected to happen**:
The helm install should succeed without warnings

**How to reproduce it** (as minimally and precisely as possible):

Create repro.yaml:
```yaml
couchdbConfig:
  couchdb:
    uuid: 123

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: "app"
              operator: In
              values:
              - couchdb
        topologyKey: "kubernetes.io/hostname"
```
Then run `helm install my-name couchdb/couchdb -f repro.yaml`

**Anything else we need to know**:
It seems to be tied to having `affinity:` defined in values.yaml without any children. If I comment out this line, the release succeeds without errors and creates the affinity
https://github.com/apache/couchdb-helm/blob/deb055f1c11696fb847e177c14176c1f217890cd/couchdb/values.yaml#L87

I know this isn't the only place that a key is defined without children though, so I'm trying to figure out if there's a better way.
